;(function(){
var f=/msie (\d+)/i.exec(navigator.userAgent);
if(f=!(!f||!+f[1])){var g,h=window.Element||(window.Element={}),i=h.prototype||(h.prototype={});isCssClass=function(b,c){return!!~(" "+b.className+" ").indexOf(" "+c+" ")};emulateDetailChildrenOpenClose=function(b,c){for(var d=-1,a,e,l;a=b.childNodes[++d];)if(1==a.nodeType)if("SUMMARY"==a.nodeName.toUpperCase()||isCssClass(a,"\u25bc\u25bc")){for(l=-1;!e&&(e=a.childNodes[++l])&&!isCssClass(e,"details-marker");)e=void 0;e&&(e.innerHTML=c?"\u25bc":"\u25ba")}else a.style.display=c?"":"none"};_openAttributeReplacement=
"OPEN";var k={get:function(){return!("nodeName"in this)||"DETAILS"!=this.nodeName.toUpperCase()?void 0:null!==this.getAttribute(_openAttributeReplacement,1)},set:function(b){if("nodeName"in this&&"DETAILS"==this.nodeName.toUpperCase()){var c=function(){j.call(d,event)};if(!this.a||!this.a.__isShimmed){this.a||(this.a={});g?b="open"in this.attributes:(b=null!==this.getAttribute("open"),Object.defineProperty(this,"open",k));this.removeAttribute("open");b&&this.setAttribute(_openAttributeReplacement,
"",1);for(var d,a,e=-1;a=this.childNodes[++e];)3===a.nodeType&&/[^\t\n\r ]/.test(a.data)?(this.insertBefore(document.createElement("x-i"),a).innerHTML=a.data,this.removeChild(a)):"SUMMARY"==a.nodeName.toUpperCase()&&(d=a);d||((d=document.createElement("x-s")).innerHTML="Details",d.className="\u25bc\u25bc");this.insertBefore(d,this.childNodes[0]);document.createElement("x-i");d.insertAdjacentHTML("afterbegin","<x-i class=details-marker>"+(b?"\u25bc":"\u25ba")+"</x-i>");d.tabIndex=0;d.attachEvent("onclick",
c);d.attachEvent("onkeyup",c);this.a.__isShimmed=1}a:{c=RegExp("(^|\\s)\u25ba(\\s|$)","g");a=this.className;if(b)a=a.replace(c,"$1");else{if(c.test(a))break a;a+=" \u25ba"}this.className=a.replace(/\s+/g," ").replace(/(^ | $)/g,"")}b?this.setAttribute(_openAttributeReplacement,"",1):this.removeAttribute(_openAttributeReplacement,1);emulateDetailChildrenOpenClose(this,b);return b}}};Object.defineProperty&&Object.defineProperty(i,"open",k);!("open"in i)&&!("getopen"in i)&&(i.getopen=k.get,i.setopen=
k.set,g=!0);g&&(_openAttributeReplacement="OPEN");document.head.insertAdjacentHTML("beforeend","<br><style>details summary,details .\u25bc\u25bc{display:block}details{display:block"+(g?";behavior:url(/Element.details.ielt8.htc)}":"}")+"</style>");var j=function(b){(b.keyCode===13||b.type==="click")&&k.set.call(this.parentNode,!k.get.call(this.parentNode))},m=function(){for(var b=document.getElementsByTagName("details"),c,d=-1;c=b[++d];)k.set.call(c,k.get.call(c))};"complete"!=document.readyState?
(void 0===document.readyState&&m(),document.addEventListener?document.addEventListener("DOMContentLoaded",m):window.attachEvent("onload",m)):m()}
})();
